### ISSUE TITLE
Editor strips images and other data  from problems

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#12]
Steps to reproduce:
Log into PA account and navigate to the Play Area
Choose a question bank
Click "Edit" on a problem  that contains an image, table, math equation, icon, Introduction, parabox, or multiple choice selection.

Result: neither the image(s) nor the other elements listed above are visible in the editor. If the problem is saved at this point those elements are lost. Before and after data from problem -684769484 is shown below:

BEFORE EDIT
<xmp>Stem html 
 <p>Which economic system is shown in this diagram?</p> <p> <img data-width="1300" data-height="428" data-dpi="300" style="width: 433px; height: 143px;" alt="STX16734.PNG" src="/easdata/STX16734.PNG" /> </p> <ol class="emcee" data-eas-hiding="false"> <li>socialism</li> <li>manorialism</li> <li>laissez-faire capitalism</li> <li class="correct">mercantilism</li> </ol> </html>
Stem tex 
Which economic system is shown in this diagram? \figure{STX16734.PNG} \emcee[hiding=false]{ \mc socialism \mc manorialism \mc laissez-faire capitalism *\mc mercantilism }</xmp>

AFTER EDIT
<xmp>Stem html 
<p>Which economic system is shown in this diagram?</p> <p> </p> <p>socialism</p> <p>manorialism</p> <p>laissez-faire capitalism</p> <p>mercantilism</p>
Stem tex 
Which economic system is shown in this diagram? socialism manorialism laissez-faire capitalism mercantilism
</xmp>

**Comment by gcortright** [comment]
@Reinmar I have verified that the image reference is present in the JSON that gets passed to the editor. So, I can confirm the correct data is getting passed, but the editor is somehow ignoring or removing the image reference it is given. 

If you do not have a problem with an image in it to choose, you can always edit any problem, click insert icon, or insert images button in the editor, add an image, and then save the problem. You will see the image appear in the problem thumbnail after saving. If, however, you attempt to re-edit the problem you will see that the image is not loaded into the editor.

**Comment by Reinmar** [comment]
From what I can see you don't have the [`config.allowedContent`](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-allowedContent) configured and while porting your features to CKE4 I didn't work on automatic integration with the ACF as I wouldn't be able to predict the whole scope of the features anyway.

Please see the [Content Filtering](http://docs.ckeditor.com/#!/guide/dev_acf) guide.

The simplest option, but definitely not perfect is using `config.allowedContent=true` to disable content filtering. This, however, disables the filter completely, so users will be able to paste mess into the editors. So I rather recommend setting the option precisely.

Alternatively, you can configure only the [`config.pasteFilter`](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-pasteFilter) to limit what can be pasted and use `config.allowedContent=true`. Unfortunately, if you won't configure it to allow exactly the content that you allow in general, then copy&paste within the editor will strip some things on some browsers.

That's why, if you can predict what kind of data you have in the database, configuring `config.allowedContent` is the best choice.

**Comment by Reinmar** [comment]
I see that I already disabled ACF here: https://github.com/educaide/ckeditor-dev/blob/master/easconfig.js#L50. Do you use the same config?

**Comment by gcortright** [comment]
@Reinmar Thanks, I had copied over that config. Not sure how I missed that line, though I have corrected that now, as well as the missing css.

**Comment by gcortright** [comment]
@gzip-pa please retest. Have retested myself with success, but independent confirmation always nice.

**Comment by gzip-pa** [comment]
fixed
