### ISSUE TITLE
Problem Editor: Inconsistant toolbar hightlighting during edit

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#26]
_From @gzip-pa on June 26, 2015 16:57_

In general, when you are editing a problem, the toolbar icon for the feature you have selected is highlighted. For example, when your cursor is in a centered block of text, the 'centered' icon is highlighted. If it is a left-aligned list, both the left-aligned and list toolbar icons are highlighted.

Inconsistencies: 
When you select a table, image, symbol, paragraph box or math formula, those toolbar icons are not  highlighted (I am told this feature worked at one time).

If your document contains an introduction, the introduction toolbar icon remains highlighted no matter what element you have selected.

_Copied from original issue: educaide/hachiko#460_

**Comment by Reinmar** [comment]
There's a difference between features like bold or centering and tables or images. When you're inside a bolded text the bold button should be "on", because there's also an "off" state available (no bold). This is not true when you're in a table - you cannot just "off" the table and you can actually add another table into the current one.

So the current behaviour is totally correct. I'm closing this ticket as invalid. The only correct part is:

> If your document contains an introduction, the introduction toolbar icon remains highlighted no matter what element you have selected.

I moved it to #38.
