### ISSUE TITLE
Entering and exiting the math quill span

### ISSUE THREAD

**Issue by gcortright** [educaide/ckeditor-dev#42]
To start a math quill span/text area in the editor a user must use `cntrl/cmd + m`. To get out of the math quill span/text area, a user must click somewhere outside of it. A user should be able to use `cntrl/cmd + m`  or `enter` to close the math quill span/text area. That is, if the math quill span/text area has the focus, a keypress of `cntrl/cmd + m` or `enter`, should give focus back to the editor. 

Additionally, the cursor behavior on exit of the math quill span/text area needs improvement. Currently, if you have a math quill span on the left, and you click outside of the span/text area to close it, your cursor ends up far to the right of the span/text area, as seen below. 
![screen shot 2015-12-10 at 10 34 14 am](https://cloud.githubusercontent.com/assets/1951305/11724550/9f9afe94-9f29-11e5-8d1c-ffb24b68446c.png)

The behavior changes slightly when your math quill span/text area is closer to the right edge of the body of the editor, but is still strange. The rule should be that on exit of the math quill span/text area, your cursor sits a space away from the end of the math quill span/text area.

**Comment by mlewand** [comment]
As for the first part the fix is fairly simple, you could just add a key listener to the `textarea` element. I've pushed a sample solution to `ticket-42` branch.

As for the second part I can't reproduce it, at least using Google Chrome. Can I ask you to provide the browser that you've used, and step by step test case that led to the described issue?

Also a suggestion: now that we have a hotkey for leaving MathQuill widget edition, I don't se a way to edit the widget using only the keyboard. Do you feel the same way?

**Comment by gcortright** [comment]
@mlewand Yes, that is correct: with the hotkey the same for creating and exiting the widget, a user would have to click on an existing mathquill span to get into it. One thing we probably want to implement in the future is the ability to enter and exit the span with arrow keys, which would help with what you pointed out.

I will update with details on the second part.

**Comment by gcortright** [comment]
@mlewand Looking at where the focus is being set after the second cntrl/cmd + m keypress: we don't want focus returned to the widget wrapper. The focus should be returned just after the widget. That is, back to the editor body: the end of the <p> tag that the span is in. This should be so that the user can continue on as normal in the editor.
